// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_intermediate = "CgkI9faw0sUUEAIQBA"; // <GPGSID>
        public const string achievement_advanced = "CgkI9faw0sUUEAIQBQ"; // <GPGSID>
        public const string achievement_beginner = "CgkI9faw0sUUEAIQAw"; // <GPGSID>
        public const string leaderboard_most_megs_in_a_round = "CgkI9faw0sUUEAIQAQ"; // <GPGSID>
        public const string achievement_master = "CgkI9faw0sUUEAIQBg"; // <GPGSID>
        public const string achievement_double_meg = "CgkI9faw0sUUEAIQBw"; // <GPGSID>

}

